### ISSUE TITLE
Allow to run scheduled jobs with drain_queue/1

### ISSUE THREAD

**Issue by maltoe** [sorentwo/oban#101]
Hey @sorentwo,

here's another odd feature request 🍰 

### Problem

In integration tests, we would like to be able to run scheduled jobs by calling `drain_queue`.

### Solution

Not sure exactly, haven't read to much of the `Producer` yet

### Current Workaround

We currently have a test helper that looks somewhat like this:

```elixir
  @doc """
  Allows to flush scheduled workers from Oban queues.
  """
  def drain_queue_including_scheduled(queue) do
    queue |> to_string() |> clear_scheduled()

    Oban.drain_queue(queue)
  end

  defp clear_scheduled(queue) do
    from(j in Oban.Job, where: j.queue == ^queue and j.state == "scheduled")
    |> MyRepo.update_all(
      set: [
        scheduled_at: DateTime.utc_now(),
        state: "available"
      ]
    )
  end
end
```

What do you think?

cheers,
malte

**Comment by sorentwo** [comment]
@maltoe Another interesting case you've brought up. I've been thinking about this for a couple days now and I'm debating between a few options:

1. Automatically run scheduled jobs when the queue is drained. This would be the most convenient for testing, but could be unexpected outside of a test environment.
2. Add an option to `drain_queue` that will automate the `scheduled_at` time before draining the queue. That could look like `Oban.drain_queue(queue, with_scheduled: true)`, though I'm not set on a name.

I'm leaning toward the second option because it makes the choice explicit. What do you think?

**Comment by maltoe** [comment]
👍 Agree that executing scheduled jobs with `drain_queue` deserves an option. Even just `scheduled: true` would be clear, in my opinion.

**Comment by maltoe** [comment]
Any plans yet on how to implement this? My guess would be that [`Query.stage_scheduled_jobs`] could be parametrized to ignore the `scheduled_at`?

**Comment by sorentwo** [comment]
Hmm. `Query.stage_scheduled_jobs` could have a third argument that is a time stamp. Instead of always scheduling jobs before `utc_now` it would accept a value that is far in the future.

**Comment by maltoe** [comment]
I might be able to get some hours to work on this, if you haven't started already. Might take a couple days, though.

**Comment by sorentwo** [comment]
It’s all yours. No rush on my part :+1:
