### ISSUE TITLE
`FunctionClauseError` in `Registry.keys/2`

### ISSUE THREAD

**Issue by whatyouhide** [sorentwo/oban#1060]
### Environment

- PostgreSQL Version: 13.2
- Elixir: 1.16.1 (compiled with Erlang/OTP 26)
- Erlang: 26.0.2
- Oban:

![CleanShot 2024-03-26 at 13 09 40@2x](https://github.com/sorentwo/oban/assets/3890250/105dfc52-704d-4ec3-ae1f-c43a518917ab)

### Current Behavior

We got a few `FunctionClauseError`s whose stacktrace is completely Oban. We might be doing something wrong, but I thought I'd check in anyway 😉 

Here is the stacktrace:

![CleanShot 2024-03-26 at 13 11 06@2x](https://github.com/sorentwo/oban/assets/3890250/b7adef9f-f47e-4b0a-993d-4a6cd6e2e52b)

**Comment by sorentwo** [comment]
Did this happen during shutdown? The issue is that `Oban.Met` is linked to the Oban supervisor process, but it doesn't stop quickly enough. You can avoid this by adding `Oban.Met` to the list of plugins and disabling auto-start with `config :oban_met, auto_start: false`.

We'll look at a better way to handle linked shutdown.

**Comment by whatyouhide** [comment]
Fantastic @sorentwo thank you! Lookinng forward to a release.
