### ISSUE TITLE
Batching Jobs

### ISSUE THREAD

**Issue by TheFirstAvenger** [sorentwo/oban#121]
### Is your feature request related to a problem? Please describe.

We are looking to use batching with Oban, but not in the way your blog post discusses, it is more in the way that broadway handles it. The issue is that we have events happening, and we want to execute all the pending jobs together in one process as soon as a batch_size is reached, or a batch_timeout happens, e.g. every 500 items or 1,000ms.

### Describe the Solution You'd Like

A queue that is configured as a batch queue, with batch_size and batch_timeout configs. Instead of perform(job) being called for every event, perform_batch(jobs) would be called when the batch_size or batch_timeout is reached.

### Describe Alternatives You've Considered

We currently are using Broadway/SQS for this, but would rather it be done in Oban.

**Comment by sorentwo** [comment]
As discussed on Slack, I think this type of batching is an interesting and perfectly viable use case. It presents some design challenges which I'll try to sketch out / talk through here.

### Batch Configuration

- **Pro** — Requires no additional configuration
- **Con** — Batching behavior is implicit, no way to specify a worker specific batch limit or timeout

2. Explicit — Specify batch behaviour at the queue level by specifying batch options. This specifically sets a producer to operate in batch mode and sets the poll interval to a custom value. Configuration would look somewhat like this:

```elixir
queues: [default: 10, small: [size: 100, timeout: 1000], large: [size: 500, timeout: 5000]]
```
- **Pro** — Clearly identifies batch queues, specifies batch size, specifies a timeout
- **Con** — Can't mix single and batch jobs on a single queue

### Worker Changes

Worker's will have a new `perform_batch/1` callback which accepts a list of `Job` structs to process. The signature would look like this:

```elixir
@spec perform_batch(jobs :: [Job.t()]) :: :ok | {:error, [Job.t()]}
```

This prompts some questions:

- There is a discrepancy between `perform/2` and `perform_batch/1`. It doesn't make sense to pass a list of args and a list of jobs into `perform_batch`. Is that a problem?
- Does the batch need to succeed or fail as a whole? This is how broadway would do it and it makes handling the return value more obvious.

Thoughts?

**Comment by mcrumm** [comment]
@sorentwo Thanks for taking the time to consider this feature! @TheFirstAvenger asked me to share some thoughts from a conversation we had recently.

> Does the batch need to succeed or fail as a whole? This is how broadway would do it and it makes handling the return value more obvious.

Broadway doesn't actually require succeeding/failing batches as a whole. Messages are automatically acknowledged as successful _unless_ you fail them in a callback, but this applies on a per-message basis:

```ex
# lib/my_broadway.ex
alias Broadway.Message

def handle_batch(_batcher, messages, _batch_info, _context) do
  # The only hard requirement for the handle_batch callback is that
  # we must return the entire list of messages.
  Enum.map(messages, fn message ->
    if valid?(message.data), do: message, else: Message.failed(message, :invalid)
  end)
end
```

Ideally we'd be able to do the same thing in a `perform_batch/1` callback. That might require being able to mark an individual Job as failed before it's returned from the callback, as opposed to having the tagged tuple specify the result of the entire batch.

**Comment by sorentwo** [comment]
Thanks for the update @mcrumm!

> Broadway doesn't actually require succeeding/failing batches as a whole. Messages are automatically acknowledged as successful _unless_ you fail them in a callback, but this applies on a per-message basis:

Interesting. Admittedly I haven't used broadway, I've only ready about it a little. Looks like I need to do some research 😞 

> Ideally we'd be able to do the same thing in a `perform_batch/1` callback. That might require being able to mark an individual Job as failed before it's returned from the callback, as opposed to having the tagged tuple specify the result of the entire batch.

Though `perform_batch/1` would be a distinct function with some differences to `perform/2`, I'd prefer that they operate with the same paradigm and use tagged tuples for the results. I think we can work out tuples that communicate success or failure at the batch and individual levels.

My first instinct is to use return values like `perform/2`, with the addition of a tuple to fail a subset of jobs:

* `:ok` — succeed the entire batch
* `:error`, exception raised or an exit — failure the entire batch
* `{:error, [Job.t()]}` — fail all of the jobs listed

That may not be detailed enough (no message), but it wouldn't be a departure from the current paradigm.

Thoughts?

**Comment by mcrumm** [comment]
I think that would work! Likewise, I'm not as familiar with Oban internals, but I don't see any virtue in adding a failure reason just to signify a failure on an individual job in a batch.  Further, Broadway has no built-in retry mechanism like Oban, so failure is more temporal here.

**Comment by sorentwo** [comment]
This isn't forgotten! Currently I'm focused on getting 1.0 released. After that I'll focus on batching jobs.

**Comment by tnpxu** [comment]
Suggestion on Batching Jobs feature:
- Is it possible to replicate the batching jobs like Celery Workflow
- ref: [Celery Workflow Canvas](https://docs.celeryproject.org/en/latest/userguide/canvas.html)

**Comment by sorentwo** [comment]
> Is it possible to replicate the batching jobs like Celery Workflow

This feature aims to make processing multiple jobs simultaneously possible, where jobs are processed within a single function call.

There are some interesting concepts (and terminology) in the celery workflow you linked. Many of the "primitives" can be replicated using Oban entirely within your application: group, chain, chord and map. The other two primitives, starmaps and chunks, are precisely what this feature request is about.

**Comment by mindreader** [comment]
I think this may solve a problem we are having, if it existed, so I would put my use case for this.

We have jobs where you publish a podcast, it takes about 10 seconds to generate all the data necessary, and then inform all sorts of services that they should fetch this new rss feed and log all their responses and such.  The thing is that a lot of things can trigger a republish of a podcast.  Publishing a new episode, uploading an audio file, just changing the title of an episode and they can happen at arbitrary times, sometimes rapidly and the final state counts.

What I started with was a unique worker that would not spawn a new job when one was already queued or executing.  The problem is that when one was executing and a new update came in, a new job would be dropped, but that update is needed as the currently executing job doesn't have fully up to date information.

What I ended up doing was having a unique worker but only for queued jobs, and then a 10 second delay.  Then jobs will queue and duplicate jobs will not end up in the queue and existing job will finish before a new one executes.  The downside is that it takes 10 seconds to republish a podcast if there's only one event.

If there were a batch job, I could take the unique job constraint out and just let them all queue up and then every few seconds, deduplicate the jobs and process them all and that would be incredibly useful.

**Comment by ernbrn** [comment]
I previously come from Ruby-land and really enjoyed Sidekiq's batch functionality. We recently wanted to use a similar pattern with Oban, and I ended up rolling my own. 

I don't think it has quite the interface discussed here, but I wanted to share it anyway, so I pulled it out into its own repo: https://github.com/ernbrn/oban_batch.

Out of curiosity, where does built-in batch functionality fall in the roadmap?

**Comment by sorentwo** [comment]
@ernbrn Awesome to see that you've built something on top of Oban!

As discussed briefly on Slack, this issue is requesting batch jobs in the Broadway sense, not in the Sidekiq sense. Batch functionality in the Broadway sense is on the roadmap, but there are some bigger changes in the works right now before I can dedicate any time to it.

**Comment by LostKobrakai** [comment]
I've not used broadway yet, but wouldn't it be enough to have an oban producer? Then the batching and such could stay in broadway.

**Comment by sorentwo** [comment]
This is landing in the next Pro release as the Chunk Worker. Thanks for all of the thoughtful discussion!
