### ISSUE TITLE
arguments worker keys in map are converted?

### ISSUE THREAD

**Issue by jesuiswu** [sorentwo/oban#126]
Am I wrong, or are atom keys of maps converted to string when passing as an argument to the worker def perform( .. 

I have a pretty big map as argument, and it seems unusable in this state .. 

🤔😬

**Comment by sorentwo** [comment]
The args are serialized as `jsonb`, which means they are deserialized with string keys. Deserializing to atom keys is unsafe because it provides an attack vector to exhaust the available atoms. This is the same reason that plug/Phoenix args are passed as strings.

Regardless, there isn’t a limit to the size of the args map.

**Comment by revati** [comment]
Ability to provide custom serialiser that can call `Jason.decode(raw_body, keys: :atoms!)` or something would be great tho
