### ISSUE TITLE
First deploy: start the application without the migrations

### ISSUE THREAD

**Issue by philss** [sorentwo/oban#13]
Hi. First of all, thank you for the project!

We are running our first deploy with Oban and we had to remove it from the supervision tree for the first deploy. This is because our application couldn't find the table `oban_jobs` and [was crashing because of this](https://gist.github.com/philss/ac3923f229ea790cee659c5b57756edd).

Our solution was to comment that line that add the Oban application to the supervision tree, deploy and migrate, comment out and deploy again. 

Is there a best practice or a recommendation to deploy the application with Oban for the first time?

There is a detail about our project: we are using [Mix release](https://hexdocs.pm/mix/1.9.0-rc.0/Mix.Tasks.Release.html#content).

**Comment by sorentwo** [comment]
@philss Thanks for reporting the issue. I admit, I haven't used the new release task yet and hadn't ran into this.

I'll work on instructions for avoiding this issue, and possibly make some changes to prevent it from happening entirely. My goal is to have as few manual steps for users as possible—the project should feel like it "Just Works", and crashing on initial boot definitely isn't "just working".

**Comment by philss** [comment]
@sorentwo Thank you for the clarification. The commit you mentioned seems to mitigate the problem. I will try this soon.

**Comment by sorentwo** [comment]
@philss That was only a partial solution, I plan on writing some release specific deployment docs as well.

Currently I'm debating between two alternative solutions:

1. Catch failing queries from the producer and log them as errors rather than crashing the process. This would prevent the queue supervisor from crashing, which would prevent the cascade that can bring down the system.
2. Document that for the initial deployment Oban should not be started, or at the very least queues must be disabled. That seems like a bit of a hack and puts the burden of sequential deploys on developers.

I'm leaning heavily toward the first option and calling it "resilient" mode. It would be the default mode, which could be disabled if you'd prefer to have a crash.

Thoughts?

**Comment by lucasmazza** [comment]
@sorentwo the 1st option seems to be a good approach - oban could check if the expected table exists, log that the database needs to be migrated and sleep for a few minutes, so the system can recover if the table is created right away. This mechanism could help future upgrades that require database changes and people might not noticed it when updating the dependency.

**Comment by philss** [comment]
@sorentwo I like the approach of the 1st option, and like @lucasmazza suggested, it could check if the database is ready to run jobs and log the errors if not.

**Comment by sorentwo** [comment]
The first option is in master and will be in v0.4 that I'm about to release. There is a small blurb about it in the [README](https://github.com/sorentwo/oban#note-about-releases) and a bit more detail in the [CHANGELOG](https://github.com/sorentwo/oban/blob/master/CHANGELOG.md#added) under `[Oban.Queue.Producer]`.

Thanks again for the report. Hopefully this improves the deployment process for everybody as more and more people move to use releases.

**Comment by philss** [comment]
@sorentwo awesome! Thank you!
