### ISSUE TITLE
Advice on "stuck" jobs?

### ISSUE THREAD

**Issue by coladarci** [sorentwo/oban#169]
I woke up to find 5 jobs that were in the state of "executing" - they are all jobs that should only take a few seconds but were attempted a day or so ago. These "stuck" jobs cause some big problems in my world and while I imagine I can manually flip them into a new state so they can be picked up again, I'm curious if you have any ideas on how to more correctly solve this? Job timeouts? Etc..

Thank you again for such a great library..

**Comment by sorentwo** [comment]
Job timeouts seem perfect for this situation. Fortunately there is [work in progress for that exact feature](https://github.com/sorentwo/oban/pull/156)!

I'm curious how those jobs got stuck in the `executing` state though. Do you know if the processes are/were alive as well?

**Comment by coladarci** [comment]
Thanks, yeah the timeout will help me quite a bit; in my case I'd set something pretty high and allow a retry if it ever was hit.

I'm not entirely sure how to answer your question, if you have any advice on how to debug this I have left it "stuck". 

My 4 stuck jobs all were all attempted by this node
![image](https://user-images.githubusercontent.com/1004167/74180303-226e9f80-4bf4-11ea-898b-1c3d316be5a5.png)

And when looking at the `beats` table, that node appears to continue to be there.. 

Any ideas on what else I can look into?

**Comment by coladarci** [comment]
Just an update, I flipped them to retryable so that my system could get back healthy; timeouts will likely solve my problem.. thanks for the quick response!

**Comment by coladarci** [comment]
Sorry, another update; I thought this was just a one-off (as it only happened once) but we have moved our code to our production env and it's become a big problem. We have a job that schedules jobs who schedule jobs, etc; that whole treat takes about 20 minutes to shake out. I now have about 5-10 jobs out of the thousands who will get "stuck" every time. Each time it's a different set of jobs, different queues. I can't find anything they have in common and since I don't have a way of seeing the "output" of that job, I am having an extremely hard time even debugging this.

I am about to write a separate cron that goes and flips stuck jobs into retryable to put out this fire, but I wanted to throw this out here. 

Theoretically, there's *never* a reason a job should be stuck, right?  i.e it's not that my job sometimes returns an invalid payload that Oban doesn't recognize?

**Comment by sorentwo** [comment]
> Theoretically, there's never a reason a job should be stuck, right? i.e it's not that my job sometimes returns an invalid payload that Oban doesn't recognize?

There isn't a reason that any job should get stuck in the "executing" state. The return value is ignored unless it is `{:error, reason}`, in which case it wouldn't be stuck since it would be marked as a failure.

A few questions off the top of my head:

1. Are the stuck job ids reported in the `running` column for the beats on that queue?
2. Are you able to connect to the running node? If so, can you see if the jobs/pids are tracked by the producer for your queue? You can get the state with this:

    ```elixir
    Oban.Queue.NameOfYourQueue.Producer |> :sys.get_state() |> Map.get(:running) |> Map.values()
    ```

    The result will be a list of tuples where the first element is the job and the second is the pid.

3. If the job id _is_ listed in the running state can you see if the process is alive with `Process.alive?/1`

If the processes are still alive then something seems to have hung the process.

**Comment by coladarci** [comment]
(moving this to slack)

**Comment by RodolfoSilva** [comment]
Hey @coladarci, I'm facing the same issue in production. How did you solve this problem?

**Comment by sorentwo** [comment]
@RodolfoSilva This issue was from years ago, and a lot has changed in the meantime. There's a guide to help troubleshoot stuck jobs now: https://hexdocs.pm/oban/troubleshooting.html#jobs-stuck-available-and-won-t-execute

**Comment by DriesCruyskens** [comment]
I'm documenting a possible cause here because I stumbled upon this issue with the same problem a long while ago never finding a solution until I read up on how elixir handles graceful shutdowns. Elixir only shuts down gracefully on receiving the SIGTERM signal. I got jobs stuck on 'executing' during development but never in production. This is because on deployment, the app gets shutdown with a SIGTERM signal (systemd) allowing the whole app to shut down gracefully (Oban included).  Pressing Ctrl-C during development does not send a SIGTERM signal but kills the app 'ungracefully' instead. If this happens while job is processing, the job gets stuck on 'executing'. (max-attempts: 1)

references:
https://felt.com/blog/startup-and-shutdown-for-phoenix-applications
https://elixirforum.com/t/how-to-handle-oban-workers-gracefully-exit-and-how-to-make-the-oban-queues-global-when-say-the-phoneix-application-is-deployed-on-multiple-nodes/34833
