### ISSUE TITLE
Error in logs around Oban.Crontab.Scheduler.handle_info/2

### ISSUE THREAD

**Issue by coladarci** [sorentwo/oban#175]
After upgrading to latest Oban I am seeing this error in my logs:

`no function clause matching in Oban.Crontab.Scheduler.handle_info/2` 
`lib/oban/crontab/scheduler.ex in Oban.Crontab.Scheduler.handle_info/2 at line 64`

Here's a screenshot of what the function is getting:

![image](https://user-images.githubusercontent.com/1004167/74788619-20958380-5267-11ea-9df8-716d51309793.png)

Is this something to be concerned about?

Thanks!

**Comment by sorentwo** [comment]
Has this happened often? That message format looks like the result of a `Task`, which is shaped like `{ref, {:ok, value}}`. The scheduler doesn't create any tasks though, which makes it strange.

Anyhow, it is only something to be concerned about if it is happening often because it'll crash the scheduler every time.
