### ISSUE TITLE
(FunctionClauseError) no function clause matching in Oban.Web.StateComponent.handle_event/3

### ISSUE THREAD

**Issue by milmazz** [sorentwo/oban#289]
## Environment

- Oban Version: Oban v2.0.0-rc.3, Oban.Web v2.0.0-alpha.1, Oban.Pro v0.2.1

### Current Behavior

The most recent version from `Oban.Web` is showing a `FunctionClauseError`, you can see more details in the following link.

https://sentry.io/share/issue/2166bbc3c6534769a3f99424022d74e5/

### Expected Behavior

`Oban.Web` should handle the event.

**Comment by sorentwo** [comment]
This is due to collisions between `myself` values in nested components. The issue was reported in https://github.com/phoenixframework/phoenix_live_view/issues/895 and fixed with https://github.com/phoenixframework/phoenix_live_view/pull/964. The fix is included in Live View 0.14, which the next version of ObanWeb supports.
