### ISSUE TITLE
Add function to restart jobs manually

### ISSUE THREAD

**Issue by sescobb27** [sorentwo/oban#309]
### Is your feature request related to a problem? Please describe.

we would like to restart discarded jobs that were attempted multiple times but because reasons couldn't complete, but after restart would complete successfully

### Describe the Solution You'd Like

right now i'm doing this, but would like to see this in the lib, and will be willing to contribute it if you accept, i know this is not enough in order to be accepted by you, but just seeing if this is something you would like to havein oban

```elixir
  def restart_oban_job(oban_job) do
	from(job in Oban.Job, where: job.id == ^oban_job.id)
    |> Repo.update_all(set: [state: "available", attempt: 0, discarded_at: nil])
  end
```

**Comment by sorentwo** [comment]
A few things to discuss before this can be made into a PR:

1. Should the attempts be reset to 0? The errors array is still intact, which means the attempt won't match up. Perhaps doubling the `max_attempts` limit would be clearer? Keeping the `attempt` would change the backoff period between retries, which is probably not desirable.
2. The `attempted_at` timestamp should probably be cleared as well
3. The function should probably be named `retry_job` rather than `restart_job`, to be consistent in terminology.

I'd also like to point out that this is built into ObanWeb 😉

**Comment by sescobb27** [comment]
Hey, agree with everything you point out, that makes sense. regarding ObanWeb we are using oban on microservices which doesn't have any public interface to the outside, everything is GRPC inside VPN so using ObanWeb its not an option, i know that is your paid service and will understand if you don't want to bring that feature to oban directly, let me know if that would be a thing you will consider, if not, we can close this no problem, either way is ok for me, thank you.

**Comment by sorentwo** [comment]
My only hesitation in adding this directly to Oban are the issues I mentioned above. I pointed out that it was included in ObanWeb in the interest of helping you more immediately, but I understand that isn't an option.

We can work out the attempt/max_attempts details in a PR, if you have the time.

**Comment by sorentwo** [comment]
@sescobb27 Is this still something you're interested in?

**Comment by sescobb27** [comment]
@sorentwo we are now using oban.pro to use other plugins and this feature, but haven't have time to do it for the community 😞
