### ISSUE TITLE
Config default max_attempts globally

### ISSUE THREAD

**Issue by rauann** [sorentwo/oban#311]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when most of my jobs have the same `max_attempts` value which is not the default value defined in the job schema field (20) and I need to define the default value that I need and it is the same in all of them.

### Describe the Solution You'd Like
Instead of having the `max_attempts` default value fixed, would it be possible to define it globally in the `config` values?

If this is reasonable I can open a PR with this feature.

**Comment by sorentwo** [comment]
All of the values stored in `config` apply to the server side, inserting and running jobs. None of them apply to the client side, where you define the workers. This separation is purposeful as it keeps your workers isolated and entirely under your control.

Defining `max_attempts` for each worker seems reasonable to me because you're making it explicit. If you must set a global value for your application you can define your own worker macro and use that instead of `use Oban.Worker`:

```elixir
defmodule MyApp.Worker do
  defmacro __using__(opts) do
    quote location: :keep do
      use Oban.Worker, unquote(Keyword.put_new(opts, :max_attempts, 10))
  end
end
```
