### ISSUE TITLE
Options validation on Oban.insert_all/2

### ISSUE THREAD

**Issue by VitorTrin** [sorentwo/oban#315]
### Is your feature request related to a problem? Please describe.

When reading the documentation for [Oban.insert_all/2](https://hexdocs.pm/oban/Oban.html#insert_all/2) I found ambiguous what it meant by unique job configuration. It's not possible to configure any per job params, or not possible to configure `:unique` related stuff? I attempted to use update_all with priority set to 4 and  it worked. Later, when I attempted to use `Oban.insert!/2`, I was surprised when I got a changeset error for priority 4.

tl,dr: I got confused by the docs and managed to insert an opt that I shouldn't  

### Describe the Solution You'd Like

Validation for opts on the `Oban.update_all/2`, and less ambiguous documentation for it. The word unique has multiple meanings.

### Additional Context
This is the latest version, 2.1.0

**Comment by halostatue** [comment]
What if there’s some sort of `Oban.verify/1` API such that `{good, bad} = Enum.split_with(all_jobs, &Oban.verify/1)`?

**Comment by sorentwo** [comment]
Both `Oban.Worker.new/2` and `Oban.Job.new/2` return an `Ecto.Changeset`, which has validation applied. Validating within your application is as easy as validating all of the changesets before passing them to insert all:

```elixir
def validate_jobs!(jobs) when is_list(jobs) do
  for job <- jobs, not job.valid?, do: raise ArgumentError, job.errors

  jobs
end

list_of_jobs
|> validate_jobs!()
|> Oban.insert_all()
```

However, I don't think that is something that library users should need to do themselves. Oban aims to be intuitive and as safe as possible, so automatic validation for bulk insert operations seems like a natural solution.

I can see this going a few directions (or a combination of a couple):

1. _(Breaking)_ Change the return type from `[Job.t()]` to `{:ok, [Job.t()]} | {:error, [Error.t()]}`
2. Modify the return type so that the success result is still `[Job.t()]`, but add `{:error, [Error.t()]}`
3. Add `insert_all!/2,4` and raise an exception on invalid changesets

Any preferences?

**Comment by halostatue** [comment]
I’m not a fan of `insert_all!/2,4`, but that’s more my preference for not using exception-raising functions. I think that `insert_all!/2,4` is the least-breaking.

**Comment by sorentwo** [comment]
For the time being I've handled this with check constraints. There is another issue, #388, which more specifically addresses unique support for `insert_all` and which we can handle separately.
