### ISSUE TITLE
Handler Callbacks for normal workers (not Batch workers)

### ISSUE THREAD

**Issue by javiercr** [sorentwo/oban#316]
### Is your feature request related to a problem? Please describe.

I'd like to build a real time notification system to inform users through websocket of the current state of a job that is being executed: whether it is still `:executing`,  it went well (`:completed`) or there was some sort of error (`:discarded`, `:retryable`).

### Describe the Solution You'd Like

Being able to use [callbacks such as the ones for `Oban.Pro.Worker.Batch`](https://hexdocs.pm/oban/2.1.0/batch.html#handler-callbacks):  `handle_attempted`, `handle_completed`, `handle_discarded`, `handle_exhausted`.

I understand that Batch jobs may be part of the Pro version (as they aren't necessary for everyone), but IMHO callbacks are really useful for everyone and it would be great to have them available for normal workers.

### Describe Alternatives You've Considered

Another option could be a single callback to be executed anytime the job change its state (passing the job as argument).
It may be interesting as well to take a look to the API for Ruby on Rails ActiveJob's callbacks:
https://api.rubyonrails.org/classes/ActiveJob/Callbacks/ClassMethods.html

Thank you and congrats for the great library!

**Comment by sorentwo** [comment]
@javiercr Good news! You can already do this using [telemetry job events] https://hexdocs.pm/oban/Oban.Telemetry.html#module-job-events. That is how logging and error reporting are handled, and you can easily add your own handlers to simulate `:handle_attempted`, `:handle_completed`, etc.

The callback form is necessary for batches because they may be distributed across many nodes and a separate process coordinates the callbacks. That isn't needed for individual jobs though.

**Comment by javiercr** [comment]
@sorentwo that's great! Sorry I totally missed that in the docs. Thank you for the prompt response! 🙌
