### ISSUE TITLE
Simple and elegant way to update Oban Job's in the DB

### ISSUE THREAD

**Issue by jfayad** [sorentwo/oban#368]
### Is your feature request related to a problem? Please describe.

New commits of Oban introduced a meta field to store extra information about a job.
Sometimes we need to update this field to keep job data up to date.

We couldn't find an easy and straightforward way to do that using Oban's modules... 

### Describe the Solution You'd Like

I think it would be nice to be able to use Oban.Repo module for that operation, even though it contains an update_all method that takes a queryable, the problem is that it requires a conf as a first parameter and it's not clear how to provide a valid conf to it.

### Describe Alternatives You've Considered

we resorted to using our own Repo module for that... even-though it worked it feels wrong.

**Comment by sorentwo** [comment]
Using your own Repo module is ideal for updating jobs in the DB.

Calls to `Oban.Repo` are only proxies for calls to your `Repo`, only through configuration. Even then they're using the same `update` and `update_all` calls provided by `Ecto.Repo`.

Here is an example of adding an arbitrary value to the new `meta` field:

```elixir
def perform(%{meta: meta} = job) do
  job
  |> Ecto.Changeset.change(meta: Map.put(meta, :new, "key"))
  |> MyApp.Repo.update()
end
```

Updating job schemas directly shouldn't feel wrong. It's the right way to do it! I think this is something that should be solved with documentation rather than code.

**Comment by jfayad** [comment]
I agree... 

If that's how it's meant to be done, then simply stating it in the documentation would actually give more confidence that it is not hackish.

Thanks
