### ISSUE TITLE
High CPU usage after sleep

### ISSUE THREAD

**Issue by tomtaylor** [sorentwo/oban#42]
Oban uses very high CPU usage when I wake my Macbook up after sleep. I often leave my development server running and shut the lid at the end of the day. When I come back the following day and open the lid my BEAM process sits using 100% of the CPU.

Observer shows me that there's a large number of messages (currently ~111000) in each queue process, e.g. `Elixir.Oban.Queue.Default`. I'm guessing there's some kind of timer function which queues messages according to when the last one was sent, and putting the application to sleep causes it to schedule a large number upon wake.

This isn't a major issue - putting the machine to sleep would never happen in production, and it's easy to kill the process and start again in development. But logging it here in case it's an easy fix!

**Comment by sorentwo** [comment]
@tomtaylor Thanks for opening this up. On the one hand, I don't know if there is anything that can be done to prevent timer messages from backing up when the system is sleeping. On the _other_ hand, that number of messages seemed excessively high and it led me to check the producer module.

There were two timers running per producer, which would have effectively doubled the number of messages to handle and duplicated the polling queries. I've pushed up a fix to address this and will be releasing v0.6.0 shortly.

**Comment by axelson** [comment]
I remember running into something like this with rabbitmq a while ago. I think I ended up turning off rabbitmq before I put my laptop to sleep :(

@sorentwo could you describe a little more what the problem is? I think I'd like to start a discussion on it in on the ElixirForum (on the general topic of sleeping and timers).

**Comment by sorentwo** [comment]
> could you describe a little more what the problem is? I think I'd like to start a discussion on it in on the ElixirForum (on the general topic of sleeping and timers).

Sure, I can explain to the best of my ability.

The producer uses `:timer.send_interval/2` to repeatedly send the producer a `poll` message every second. The `:timer` module uses a separate process to manage the timer state and it will keep sending the producer the `:poll` message regardless of whether the producer has handled the previous message. Apaprently, and here I'm hypothesizing, the `timer` process either doesn't sleep when the laptop is suspended, or it tries to catch up rapidly when the laptop comes back from being suspended.

After researching the underlying issue a bit more (thanks for prompting me) I'm going to switch to using recursive `send_after` instead of utilities through the `:timer` module. That will be more efficient in overall and will also prevent this issue entirely.

**Comment by axelson** [comment]
Oh nice, that makes sense as a fix, especially given how this loop is being used :+1: 

My laptop thanks you!

**Comment by tomtaylor** [comment]
Thanks @sorentwo!
