### ISSUE TITLE
Jobs abandoned but remain in "executing" state after hot deploy

### ISSUE THREAD

**Issue by darksheik** [sorentwo/oban#430]
### Environment

- Oban Version 2.4.2
- PostgreSQL Version 11.7 (AWS Aurora)
- Elixir & Erlang/OTP Versions (`elixir --version`)
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 23)
```
### Current Behavior

We perform hot deploys using `distillery`.  Most of the time when we perform hot deploys, we have to do a bit of maintenance on our Oban queue, because things that were executing at deploy time often get "abandoned" - meaning they remain in `executing` state in the table, but they don't appear to be running.  The jobs can't be canceled through the web interface, and deleting the records from the table is the only recourse.  After the records are deleted, the workers no longer pick up new jobs and I often have to scale that queue to make the intended number of concurrent jobs begin executing again.

After scaling, we're shy of the queue's limit by the number of jobs that were abandoned.
![image](https://user-images.githubusercontent.com/654447/108240852-3e672400-7119-11eb-9e30-232b1b5f1499.png)

We performed our deploy shortly after this sample job was picked up (10:06 EST).
```
%Oban.Job{
  __meta__: #Ecto.Schema.Metadata<:loaded, "oban_jobs">,
  args: %{"company_id" => 55, "event_id" => 51384},
  attempt: 1,
  attempted_at: ~U[2021-02-17 15:06:22.389156Z],
  attempted_by: ["name@host", "barcode_matcher", "v8u5cdr4"],
  cancelled_at: nil,
  completed_at: nil,
  discarded_at: nil,
  errors: [],
  id: 110731285,
  inserted_at: ~U[2021-02-17 13:00:44.443653Z],
  max_attempts: 20,
  meta: %{},
  priority: 0,
  queue: "barcode_matcher",
  replace_args: nil,
  scheduled_at: ~U[2021-02-17 13:00:44.443653Z],
  state: "executing",
  tags: [],
  unique: nil,
  unsaved_error: nil,
  worker: "ProjectThree.BarcodeMatcherWorker"
}
```

Queue state:

```
Oban.check_queue(queue: :barcode_matcher) 
%{
  limit: 4,
  node: "name@host",
  nonce: "v8u5cdr4",
  paused: false,
  queue: "barcode_matcher",
  running: [110733413, 110731285, 110731287, 110733411],
  started_at: ~U[2021-02-10 22:44:52.497806Z]
}
```

### Expected Behavior

Oban should try to cancel these jobs and free up the worker.

**Comment by sorentwo** [comment]
It's unclear to me how this is happening and when I can hook into an upgrade to fix it.

My initial hypothesis was that a during a relup the queue producer's state was handed to a new producer process and the job's monitor was lost in the process. That doesn't hold under scrutiny for a couple of reasons:

1. The job task itself records that the job completed, yet in these cases the jobs are left in an `executing` state.
2. That's not how a hot upgrade actually works, the process stays alive and the state is handed off.

This leaves me wondering if the queue's foreman (a `Task.Supervisor`) terminating somehow? Is the job task exiting for some reason (with a pattern that doesn't match `{:DOWN, ref, :process, pid, {reason, stack}}`?

Any ideas are welcome (/cc @sasa1977).

**Comment by gvaughn** [comment]
I've been heads-down in a production issue, so I haven't had a chance to verify this (since we have a manual workaround to this), but my suspicion is that when a specific module is reloaded twice, then any process referencing the 1st version is killed. I don't have a good handle on Oban's process model to be sure how exactly this suspicion relates to the observed behavior.

The jobs we see getting stuck seem to be some of our longer running ones, but I'm not certain that is exclusively the case. We'll need to observe more. Additionally, if we observe this happening on a first hot deploy after a full release deploy, then that would invalidate my hypothesis because it relies on at least 2 hot deploys happening.

**Comment by sasa1977** [comment]
> when a specific module is reloaded twice, then any process referencing the 1st version is killed

[correct](https://erlang.org/doc/man/code.html#current-and-old-code)

There are of course other ways how the process could break. E.g. when a process calls an exported function (`Foo.bar()`), and `Foo` is reloaded, the process will switch to the new version. However, if the new version doesn't contain `bar` the process will crash. Another possible situation is calling `Foo.bar(baz)`, where the new version crashes b/c the passed `baz` structure is no longer valid.

Do you see any crash reports in your logs?

The question is how can a crash lead to the state where Oban thinks that the task is executing, but it doesn't actually run it. I'd expect the job to be picked up again after some backoff. This could perhaps be caused by the supervision tree, e.g. if some temporary process is killed, and the process tree is perpetually incomplete. I think it would be a great help if you could create a simplified project + necessary steps that reproduce the problem.

Another thing to try is manually restarting the root Oban process (in your own app tree), so the entire process structure is recreated again. If this solves the problem, it's a strong indication that some critical process was terminated and not restarted.

This is also interesting:

> The jobs can't be canceled through the web interface, and deleting the records from the table is the only recourse. 

Assuming the process crash theory is correct, it looks like Oban cancellation fails if something is "off" in the process structure. I think it's worth analyzing the cancellation logic, because that might give us a clue on what went wrong. In addition, it's worth rethinking if cancellation should fail if some expected processes are down. If Oban can't find the relevant processes, it means that the job is not executing, so deleting the db record should be fine?

> After the records are deleted, the workers no longer pick up new jobs and I often have to scale that queue to make the intended number of concurrent jobs begin executing again.

Yet another indication that something is off in the process structure.

**Comment by sorentwo** [comment]
Thanks @gvaughn and @sasa1977 for the great insight.

The "current-and-old-code" docs were exactly what I was looking for, very helpful. This bit in particular:

> If a third instance of the module is loaded, the code server removes (purges) the old code and any processes lingering in it are terminated. Then the third instance becomes 'current' and the previously current code becomes 'old'.

That leads me to believe that it may be the worker module itself that is now "old" and getting killed. It seems more likely that an app's workers change between deploys than the queue's modules (which are definitely the same because they have an identical nonce).

Exercising a variant of this flow in the console:

```
iex(1)> {:ok, pid} = Task.start(fn -> Process.sleep(:timer.minutes(10)) end)
{:ok, #PID<0.112.0>}
iex(2)> Process.monitor(pid)
#Reference<0.3192160683.73662467.39658>
iex(3)> Process.exit(pid, :kill)
true
iex(4)> flush()
{:DOWN, #Reference<0.3192160683.73662467.39658>, :process, #PID<0.112.0>, :killed}
```

Shows that the `:DOWN` message will never match one of the [handle_info clauses](https://github.com/sorentwo/oban/blob/master/lib/oban/queue/producer.ex#L73). This led me to the correct fix in f1b3705.

> Assuming the process crash theory is correct, it looks like Oban cancellation fails if something is "off" in the process structure. I think it's worth analyzing the cancellation logic, because that might give us a clue on what went wrong. In addition, it's worth rethinking if cancellation should fail if some expected processes are down. If Oban can't find the relevant processes, it means that the job is not executing, so deleting the db record should be fine?

This is a great point. The cancellation flow was broken in this case and needed some simplification. I've [addressed that](https://github.com/sorentwo/oban/commit/c335425f148aba94334f3a85c2ff76210f9fc17f), though as noted in the commit message that was a band-aid and not the proper fix.

**Comment by darksheik** [comment]
Great!  Thank you.  We usually do a couple of hot deploys per day.  We'd be happy to try this out for you if you think it's safe to use the current master.  I may not have an answer for you until the afternoon, as the jobs which usually remain hanging launch around that time.

**Comment by sorentwo** [comment]
If you’re ok using master then please, do give it a try. Having the fix verified would be fantastic before the next release—this was the last issue blocking v2.5.

**Comment by darksheik** [comment]
Good News!  We did two hot deploys this afternoon and none of the jobs that have been getting routinely stuck in these states did so.  We'll continue to use this commit instead of the previous release and report if that changes over the next few days.

Thanks as always for your speedy response.
