### ISSUE TITLE
Registry.select/2 undefined in 1.8

### ISSUE THREAD

**Issue by HangingClowns** [sorentwo/oban#437]
### Environment

- Oban Version master/HEAD
- PostgreSQL Version n/a
- Elixir < 1.9

### Current Behavior

`function Registry.select/2 is undefined or private.`

### Expected Behavior

Error/shouldn't compile cause that function isn't available and the Mix file should be set to `~>1.9` OR a workaround for `1.8`

**Comment by HangingClowns** [comment]
I don't mind to do a PR. Was thinking we can set this to at least 1.9 (of course easiest method), but not sure if you want to keep 1.8.

**Comment by sorentwo** [comment]
Elixir 1.9 is about a year and a half old, which isn't a particularly long time. There is a single feature from 1.9 that is used now, `Registry.select/2` (though that is bound to change with time).

I'm open to a workaround for `Registry.select/2`, possibly making use of `Registry.match/3`? Otherwise, bumping the minimum version to 1.9 seems reasonable. We can keep this open for a day or two to see if there are objections.
