### ISSUE TITLE
Unify job execution during runtime and testing

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#466]
### Is your feature request related to a problem? Please describe.

There are differences between how a job is executed by `perform_job` and during runtime through the `Executor` module. Most notably, `perform_job` doesn't emit any telemetry events.

### Describe the Solution You'd Like

Use the `Executor` module to exercise `perform` functions.

### Describe Alternatives You've Considered

Accept that there are subtle differences and document them.

**Comment by milmazz** [comment]
Hey :wave:  @sorentwo I just started looking at this issue, and it seems like an interesting problem. 

The current implementation of `perform_job/3` is like this:

https://github.com/sorentwo/oban/blob/d5cc908ef440dbe8532bb462db02ba7ee72c7b5f/lib/oban/testing.ex#L202-L220

So, if I got your proposal right, you're suggesting to change the way we create the `result` binding, using the `Executor` instead of doing a direct call to `worker.perform()`. But to use the `Executor.call/1` function we need to build first an `Executor` struct using for example `Executor.new/2`, where the first argument is an `Oban.Config` struct, so, my first question is, how do we capture that config at _runtime_ without introducing a _backward incompatilbility_?

Our new `result` could be something like this I guess:

```elixir
      result =
        [repo: MyRepo]
        |> Oban.Config.new()
        |> Executor.new(job)
        |> Executor.call()
```

But then, we need to capture the `Oban.Config` struct first. Any suggestion?

Also, I think we need to change the `changeset` to introduce the `attempted_at`, and `scheduled_at` to avoid issues here with `DateTime.diff/3`:

https://github.com/sorentwo/oban/blob/d5cc908ef440dbe8532bb462db02ba7ee72c7b5f/lib/oban/queue/executor.ex#L121-L127

Please let me know your opinion about this issue. Also, I don't know if someone else is working on this at the moment.

**Comment by milmazz** [comment]
@sorentwo Thanks for your guidance, I'll start working based on your feedback. I'll report back soon<sup>TM</sup>
