### ISSUE TITLE
Make snooze not affect default retry backoff base

### ISSUE THREAD

**Issue by nirev** [sorentwo/oban#476]
Hello!

I was a bit surprised by this behaviour, and not sure about the best way to report it.
I don't think it's a bug per se, so I created a feature request.

If you think the current behaviour should stay, I think it warrants a note in the Worker documentation, though.

Thank you!

### Is your feature request related to a problem? Please describe.

I caught me by surprise that by using `{:snooze, seconds}` to postpone a job, if an error is later encountered, the snooze attempts are used to calculate the backoff.

My scenario was that I had a job X that needed to wait for a condition in order to run, in the `perform/1` function of the worker, I check for the condition, and if it's not met yet, I snooze the job. After the condition is met, I need to call a third-party API. That third party API failed, and the retry was scheduled for ~5 days in the future.

### Describe the Solution You'd Like

I think any snoozed attempt should not count for computing backoff by default. Would keeping track of `snooze count` in the `meta` field make sense?

### Describe Alternatives You've Considered

I'm fully aware that I could:
- implement this without snooze
- implement the `backoff` callback myself

**Comment by sorentwo** [comment]
There isn't any way for the worker to know whether a job was snoozed, rescued or retried. In any of those events the `attempt` is bumped by 1 when the job is fetched. The only difference is whether the `max_attempts` are bumped. If the job is snoozed or rescued `max_attempts` are bumped by one to compensate.

Within your worker you can override the `backoff` to compensate for snoozes or rescues because presumably the worker knows what the original `max_attempts` value was. For example, you could use this to correct the attempt and call the default backoff:

```elixir
@max_attempts 20

use Oban.Worker, max_attempts: @max_attempts

# ...

@impl Worker
def backoff(%Job{} = job) do
  corrected_attempt = @max_attempts - (max_attempts - attempt)

  Worker.backoff(%{job | attempt: corrected_attempt)
end
```

Tracking the number of snoozes/rescues or the original max_attempts in the meta _could_ work. I'm more inclined to document the behaviour and provide the solution above as a workaround.

**Comment by nirev** [comment]
That makes sense, and implementing the backoff callback was my solution too.

If you think the current behaviour is ok and adding more code to handle this is by default is not worth, I can send a PR with improved documentation for this case!

Thank you for the quick and detailed answer!

**Comment by sorentwo** [comment]
This is enough of an edge case and the workaround is easy enough that I'd like to keep the code as-is. A PR to improve the docs would be fantastic!

**Comment by sorentwo** [comment]
@nirev Are you still interested in opening a doc PR?

**Comment by nirev** [comment]
@sorentwo yes 🙈 
thank you again for everything!

**Comment by sorentwo** [comment]
Closing in favor of #398
