### ISSUE TITLE
Job updated to completed status without any work.

### ISSUE THREAD

**Issue by MeterSoft** [sorentwo/oban#516]
Oban 2.4.3 and 2.7.1
Elixir 1.11
PostgreSQL 9.6

i have task with next configuration
```
use Oban.Worker,
    queue: :events,
    priority: 3,
    max_attempts: 20,
    tags: ["event_invitation"],
    unique: [
      period: :infinity,
      keys: [:id],
      states: [:available, :scheduled, :executing, :retryable]
    ]
```

and create it as
```
{:ok, job} =
      args
      |> EventInvitationJob.new()
      |> Oban.insert()
```

in perform method i have logger with some messages and my logic. In some reason after create job it set to completed status but perform method not calling

**Comment by sorentwo** [comment]
Are you sure that is your Postgres version? The minimum supported version for Oban is 9.6. From the README:

> Running Oban requires Elixir 1.9+, Erlang 21+, and PostgreSQL 9.6+.

Otherwise, does your `perform/1` function have multiple clauses? Have you used `Oban.Telemetry.attach_default_logger/1` to see if the job is logged? Is this something that happened once, or is it repeatable?

**Comment by MeterSoft** [comment]
@sorentwo Sorry, correct, postgres 9.6.
my perform/1
```
def perform(%{args: args} = _job) do
    LocalLog.debug("start")
    do_work()
    :ok
  end
```
I dont use default logger just see status in database. I also tried create job with delay. First it created in database with status scheduled and after N seconds changed to completed but not have any messages in log

**Comment by sorentwo** [comment]
It seems like the issue is with your logging, not the job running. Perhaps the log level is set to `:info` rather than `:debug`?

If the state is successfully changing from `scheduled` to `completed` then the job is running. You can either use the Oban logger to verify, or change the return from `:ok` to something like `{:error, "boom"}`. That will make the job transition to `retryable` rather than `completed`.

In any case, this doesn't point to an issue with Oban itself 🙂

**Comment by MeterSoft** [comment]
@sorentwo issue not related to logging because 1 created for example 5 jobs. 4 done as well and a see result and logs but one not

**Comment by sorentwo** [comment]
@MeterSoft Please attach the default logger or change the function output to verify whether Oban is running the jobs as expected.

**Comment by MeterSoft** [comment]
@sorentwo ok i will but it is on production server and it hart to read warn logs for me but please look in to this screen 
http://joxi.ru/bmogdBgC7QJ1Jm
this is list of created jobs with next perform/1
```
  def perform(%{args: args} = _job) do
    {:error, :nothing}
  end
```

this job should never completed but it is.

**Comment by sorentwo** [comment]
There isn't enough information there for me to help diagnose the issue. Regardless, I don't believe this is an Oban issue. For continued help will you please ask on the elixir forum or elixir slack?

**Comment by EthanLeisinger** [comment]
I would like to reopen this issue. I am having the same issue and can provide a few new details. I have found that this issue occurs more often with `MIX_ENV=prod`. I also found that it appears stopping and restarting the queue appears to fix the issue.

Regarding logs, I have a custom logger setup that was not logging any updates when the Job would be marked completed immediately. Attaching the default logger did not help in this situation. Stopping and restarting the queue got both loggers working.

I hope this can provide some more insight into what is causing this issue.

**Comment by sorentwo** [comment]
@EthanLeisinger To help diagnose this issue I'll need a lot more information. For starters:

1. Your Oban version (there was a related fix for `:snooze` returns recently)
2. Some configurations, including which engine you're using (e.g. is it pro?)
3. The job definition (to see what values it's returning)
4. Job details (attempt, attempted_by, timestamps)

**Comment by EthanLeisinger** [comment]
Hey sorry for the delay on my reply! I can say we do not use the `:snooze` feature in our project at this time and we use the free, non-pro, version. The Job that we are using was not setup to return an `{:ok, ...}` tuple and that may have been the cause. I have not had a chance to validate the issue is fixed or still breaking but it worked for a short period late last week. 

If the issue arrises again I will make a new ticket, with more formal details, and link back to this for reference. Thanks for the work you've done on this project!
