### ISSUE TITLE
Make Oban.scale_queue support SmartEngine's global_limit and rate_limit configs

### ISSUE THREAD

**Issue by dsdshcym** [sorentwo/oban#525]
### Is your feature request related to a problem? Please describe.

Now Oban.scale_queue can only change the local_limit config
So I need to redeploy the app to change the global_limit (or rate_limit) configs

### Describe the Solution You'd Like

`Oban.scale_queue(queue: :default, global_limit: 50)`

It's a bit leaky to accept and validate a ObanPro concept (`global_limit`) here in a Oban function
But I don't have a better solution yet

### Describe Alternatives You've Considered

I think one reason that leads to the leaky `global_limit` option is that `queue` config is somehow coupled to the `engine` config (i.e. `global_limit` only makes sense when `SmartEngine` is used)
So I can think of 2 alternatives:
1. Accept this coupling and put `queue` configs under `engine` config: `config, :app, Oban, engine: {SmartEngine, queues: [...]}`
2. Rather than triggering this update via Notifier, maybe we can find the Producer via Registry, and call `Producer.scale_queue` directly, which then would let `Engine.put_meta` to validate the input

**Comment by sorentwo** [comment]
Thanks for the thoughtful write-up around this issue. This is the gist of #503, which I'm working on currently. My approach is to improve `*_queue` validations and delegate scale/start validation to the engines.

Regardings the alternatives you suggested:

1. Moving the queues declaration wouldn't solve the issue. In most cases, people aren't specifying `SmartEngine`, and I'd prefer to keep the queues syntax as last as possible.
2. That would work for the local node, but it wouldn't work for other connected nodes. This is because all of the `_queue` functions are globally distributed via PubSub.

This fix is a top priority!
