### ISSUE TITLE
Propagate {:error, _} when doing Oban.drain_queue(with_safety: false)

### ISSUE THREAD

**Issue by stefanluptak** [sorentwo/oban#645]
### Is your feature request related to a problem? Please describe.

When I am draining a queue with multiple jobs in it, which are not raising an exception but just returning an `{:error, _}` tuple, it's difficult to know which of the jobs failed.

### Describe the Solution You'd Like

I would like to know which job (with what args) failed with what return value. The `Oban.drain_queue` could raise it as a custom exception maybe.

### Describe Alternatives You've Considered

I considered refactoring my jobs so they will raise instead of return the `{:error, _}` tuples. I will probably do it if you'll tell me this feature request is not a good idea. :-D

### Additional Context

Just thanks a lot for Oban, it's a wonderful library.

**Comment by sorentwo** [comment]
There are two "unsafe" contexts where you'd execute jobs:

1. `Oban.drain_queue/2`
2. `Testing.perform_job/3`

Raising an exception for an error tuple works for `drain_queue` without safety, but then it breaks `perform_job`. In this situation I suggest raising instead of returning an error tuple (and I'm updating the `drain_queue` docs to match that advice).
