### ISSUE TITLE
Configurable log metadata for jobs

### ISSUE THREAD

**Issue by devonestes** [sorentwo/oban#656]
When I'm trying to see logs that emitted during the execution of a given Oban job, I need some way to identify what errors all occurred as part of the same job. I've dug through the docs pretty well and couldn't find anything that would do what I need it to do, and so right now the solution we have is to set the `Logger.metadata` for each job as it's initialized, like so:
```
  def perform(%{args: args}) do
    Logger.metadata(
      team: "my_team",
      job_id: Ecto.UUID.generate(),
      job_name: __MODULE__,
      user_id: args.user_id
    )

    # do the job...
  end
```

However, adding that for each job separately isn't super nice. Some of these things will need to be added on a per-job basis if we want them in the metadata, but at least `job_id` can be set programmatically for every job without having to add that to every job's `perform/1` definition.

### Describe the Solution You'd Like

What I'd love to be able to do is something akin to the way a `request_id` is set by a Plug middleware for HTTP requests. I don't think this needs to be full-on middleware, though - it could be set in configuration like so:

```
# config/config.exs
config :my_app, Oban, log_metadata: fn args -> Logger.metadata(job_id: Ecto.UUID.generate(), user_id: args[:user_id]) end
```

And that log metadata would then be evaluated for each job (if configured). The `args` given there would be the same `args` passed to `perform/1`.

### Describe Alternatives You've Considered

A full-on middleware system would be nice, too, but probably overkill for this exact issue at hand. Really, any way to ensure that there's a unique ID for each job in the logger metadata will suffice here. The options above are just what I've been able to come up with quickly, but I'm sure there are other ways of doing this, too!

**Comment by sorentwo** [comment]
@devonestes Thanks for the thoughtful and well-reasoned proposal! I'm not sure what this feature _should_ look like, but there are a few constraints to consider:

1. This is a worker-level concern, not a global concern. That makes it a poor fit for config.
2. Middleware is part of the Pro worker and is unlikely to become part of the basic worker.

Given those constraints, what do you think about these options:

1. Automatically add `oban_job_id` to `metadata` as part of basic job execution. That's a unique value that correlates directly to the underlying Oban job. An `oban_worker` value could be injected as well.
2. Provide an additional `Worker` callback that is invoked as part of job execution. The callback could return a map that's then used as metadata.

**Comment by milmazz** [comment]
> Provide an additional `Worker` callback that is invoked as part of job execution. The callback could return a map that's then used as metadata.

I like this idea of allowing to extend the job metadata. But it seems this will not solve Devon's issue. I understand from Devon's description that he has a lot of steps or `Logger` calls in the `perform/1` function, and he's trying to track the generated logs and group them by the Oban Worker that triggered the whole sequence of actions. That's why he uses `Logger.metadata/1` at the beginning of the `perform/1`, but he wants to avoid the `Logger.metadata` dance per every worker. Is that right, @devonestes ?

So, I _think_ that in his case, we can circumvent the _executor_ pipeline a bit :)

Let me explain; before proceeding with the `perform/1`, we know that the `[:oban, :job, :start]` _telemetry_ event is triggered, right? So knowing this, he could follow the same "pattern" of the `MicroLogger` documented in the `Oban.Telemetry` module. Because of the way telemetry handlers work, you can do the `Logger.metadata` in your handler, and it will apply that to your worker because it's the same process at the end of the day. Also, note that in the telemetry handler, you have access to the `args`, which is what he wants.

```elixir
defmodule MicroLogger do
  require Logger

  def handle_event([:oban, :job, :start], _, meta, nil) do
    %{worker: worker, args: args} = meta 
    Logger.metadata(job_id: Ecto.UUID.generate(), worker: worker, user_id: args["user_id"])
  end
end
```

HTH

**Comment by sorentwo** [comment]
Great thinking. This is a perfect job for telemetry, and probably a good candidate for a recipe guide.

@devonestes Would using telemetry fit the bill?

**Comment by sorentwo** [comment]
Since we have a viable workaround through telemetry, I'm going to close this as a "won't do." Regardless, a documentation change or guide is still welcome.
