### ISSUE TITLE
Only one node runs workers

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#702]
### Environment

- Oban Version: 2.12.0
- PostgreSQL Version: 13.6
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir 1.13.4 (compiled with Erlang/OTP 24)

### Current Behavior

When running multiple nodes the leader node is the only node with any running queues.

Here's my config. Note that both nodes are identical and they exist within a distributed cluster.

```
config :core, Oban, notifier: Oban.Notifiers.PG

config :core, Oban,
  plugins: [
    {Oban.Plugins.Gossip, []},
    {Oban.Plugins.Lifeline, []},
    {Oban.Plugins.Pruner, []},
    {Oban.Plugins.Stager, []},
    {Oban.Plugins.Reindexer, [schedule: "0 8 * * *"]}
  ]
```

### Expected Behavior

All nodes should run queues.

**Comment by sorentwo** [comment]
The leader is the only node running queues because your notifications aren't working correctly. The stager plugin only runs on the leader, and it broadcasts a notification to queues on all other nodes when jobs are available. If notifications aren't working, that broadcast doesn't make it to the other nodes.

I see that you're using the `PG` notifier. Are you running with distribution/clustering enabled? Neither notifier will work if you're running on Heroku with PG Bouncer. In that case, you'll need to run the `Repeater`, as I believe you've done in the past.

This is the _exact_ situation behind this [section in the troubleshooting guide](https://hexdocs.pm/oban/2.12.0/troubleshooting.html#no-notifications-with-transaction-pooling).

**Comment by anthonator** [comment]
> Are you running with distribution/clustering enabled?
Yes, we have a distributed setup using `libcluster` and `horde`.

> Neither notifier will work if you're running on Heroku with PG Bouncer.
We do use pgBouncer but are not on Heroku.

I don't feel like we're doing anything that should prevent notifications from working unless there's something additional that needs to be done for `Oban.Notifiers.PG` tow work. Our distributed processes have no issues communicating. The only thing I was wondering is if we should be using `Oban.Peers.Global` instead of `Oban.Peers.Postgres`. It doesn't look like pgBouncer would cause issues but I'm not sure.

**Comment by sorentwo** [comment]
The peer won't make a difference because leadership is already working, and pgBouncer doesn't impact `Oban.Peers.Postgres`. The PG notifier is a thin wrapper around `:pg`. I'd expect it to work in any distributed environment.

Maybe you can check if PG notifications are working as expected by using [listen/2](https://hexdocs.pm/oban/Oban.Notifier.html#listen/2) on one and [notify/3](https://hexdocs.pm/oban/Oban.Notifier.html#notify/3) on the other?
