### ISSUE TITLE
Jobs won't get executed if Postgresql isn't in the UTC and "timezone" isn't specified in the config [crontab]

### ISSUE THREAD

**Issue by GildedHonour** [sorentwo/oban#788]
I'm in Brazil, in UTC -3. 
I'm using Crontab plugin, with jobs supposed to run every minute. I'm trying to run Oban locally.

It'll correctly insert all the jobs in the Db with the "scheduled_at" +3h to the my **local** time which is understanable.  Nonetheless, it'll never execute any of them in the **local time zone**.

Only after have I specified in the config "timezone: America/Sao_Paulo", has it begun to execute them.

What the wtf? I've wasted hours on it. 
How to make it ignore  timezone of Postgresql and instead use UTC only, **and** execute tasks in it, regardless of the local timezone?

In the documentation "timezone" is mentioned, but the fact that it may be mandatory in some cases -- isn't.

**Comment by sorentwo** [comment]
The Cron plugin doesn't schedule jobs in the future, ever. It evaluates crontab entries every minute and inserts jobs if the expression matches the current time. Jobs that should run every minute, e.g. `* * * * *` will always match and won't consider the time zone at all.

The timezone option is merely a convenience that will let you intuitively match an hourly expression like `0 8 * * *` to "8AM in my timezone," rather than translating it to `0 5 * * *` for UTC. Regardless, the timezone has no bearing on an every-minute job.

The timezone is _never_ mandatory.

**Comment by GildedHonour** [comment]
That hasn't answered my question, nor has it addresses my issue.

**Comment by sorentwo** [comment]
The only question you've asked:

> How to make it ignore timezone of Postgresql and instead use UTC only, and execute tasks in it, regardless of the local timezone?

I explained that the timezone isn't mandatory and that `scheduled_at` has nothing to do with crontab scheduling. Oban jobs are _only_ stored with UTC timestamps.

Whatever issue you encountered wasn't because of timezones.
