### ISSUE TITLE
Postgres performance question

### ISSUE THREAD

**Issue by take-five** [sorentwo/oban#79]
Hi,

We've been running Oban on Postgres 9.5 for a couple of weeks and I've noticed that performance has degraded significantly.

We have 2 workers - one is a "normal" worker, the job is enqueued on demand by the app, another one is "recurring" worker, that reschedules itself on every run and runs every 5 seconds.

Here's how its performance looks over time (the purple line is recurring worker):
![image](https://user-images.githubusercontent.com/1209413/66392585-f38fb500-e9d8-11e9-9df8-fd3b8ce20293.png)

DB logs are full of warnings about slow queries:
```
duration: 102.274 ms  execute ecto_68: SELECT o0."id", o0."state", o0."queue", o0."worker", o0."args", o0."errors", o0."attempt", o0."attempted_by", o0."max_attempts", o0."attempted_at", o0."completed_at", o0."inserted_at", o0."scheduled_at" FROM "public"."oban_jobs" AS o0 WHERE (o0."state" = ANY($1)) AND (o0."inserted_at" > $2) AND ((o0."worker" = $3) AND (o0."queue" = $4)) ORDER BY o0."id" DESC LIMIT 1
```

But when I run this query with `EXPLAIN ANALYZE` it shows nothing:
```
# explain analyze SELECT * FROM "public"."oban_jobs" AS o0 WHERE (o0."state" = any('{scheduled}')) AND (o0."inserted_at" > '2019-10-07 11:19:46.702893') AND ((o0."worker" = 'EngagementRouter.EngagementRequests.SynchronizeExpiredRequestsWorker') AND (o0."queue" = 'engagement_requests')) ORDER BY o0."id" DESC LIMIT 1;;
                                                                                          QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=6.20..6.21 rows=1 width=257) (actual time=0.040..0.041 rows=1 loops=1)
   ->  Sort  (cost=6.20..6.21 rows=1 width=257) (actual time=0.038..0.038 rows=1 loops=1)
         Sort Key: id DESC
         Sort Method: quicksort  Memory: 25kB
         ->  Index Scan using oban_jobs_queue_state_scheduled_at_id_index on oban_jobs o0  (cost=0.42..6.19 rows=1 width=257) (actual time=0.016..0.016 rows=1 loops=1)
               Index Cond: ((queue = 'engagement_requests'::text) AND (state = ANY ('{scheduled}'::oban_job_state[])))
               Filter: ((inserted_at > '2019-10-07 11:19:46.702893'::timestamp without time zone) AND (worker = 'EngagementRouter.EngagementRequests.SynchronizeExpiredRequestsWorker'::text))
 Planning time: 0.504 ms
 Execution time: 0.106 ms
(9 rows)
```

Purging and vacuuming the table (`delete from oban_jobs where state = 'completed'`) helps, but I don't think it's a good solution.

What I can't understand is how the same query performs so differently when ran from Oban and from `psql` under `explain analyze`. And how this query be so slow on a relatively small table (about 41 MB in total).

UPD. We run Oban 0.10.0 with the latest migration applied.

**Comment by sorentwo** [comment]
Is that a custom query in your app? It doesn't look like any of the queries that Oban is performing itself. Can you show how your recursive scheduled job is enqueuing itself?

Otherwise, nothing strikes me as wrong with the query. I get `explain analyze` results similar to yours within the oban.dev database, and the in-app query timing is ~2.5ms.

```
12:08:45.453 [debug] QUERY OK source="oban_jobs" db=2.5ms
SELECT o0."id", o0."state", o0."queue", o0."worker", o0."args", o0."errors", o0."attempt", o0."attempted_by", o0."max_attempts", o0."attempted_at", o0."completed_at", o0."inserted_at", o0."scheduled_at" FROM "oban_jobs" AS o0 WHERE (o0."state" = ANY($1) AND (o0."inserted_at" > $2)) AND ((o0."worker" = 'Oban.Workers.BotCleaner') AND (o0."queue" = 'default')) ORDER BY o0."id" DESC LIMIT 1 [["scheduled"], ~U[2019-10-08 12:06:39.797909Z]]
```

That timing is for a table with 1.2 million job rows in it.

**Comment by take-five** [comment]
No, this is not a custom query, this is how we do it
```elixir
  @oban_uniqueness_config [
    period: 60 * 60 * 24,
    fields: [:worker, :queue],
    states: [:scheduled]
  ]

  def perform(args, _job) do
    args
    |> __MODULE__.new(schedule_in: 5, unique: @oban_uniqueness_config)
    |> Oban.insert!()
  end
```

**Comment by sorentwo** [comment]
Ah, of course. I used the same config to insert a job in that large table and the query time was `3.6ms`, so the origin of the query didn't make a difference.

The args aren't considered in the unique check, so it would run at most once a day based on the uniqueness config. Admittedly, that shouldn't change the performance of the query at all.

Would you mind sharing the job counts per state?

**Comment by take-five** [comment]
Sure, this is how it looks like currently:
```
   state   | count
-----------+--------
 scheduled |      1
 completed | 141463
```

**Comment by take-five** [comment]
@sorentwo any news on this issue?

**Comment by sorentwo** [comment]
Sorry, no news. I’ve been traveling and haven’t had time to look into this more.

If you can build a minimal recreation of this it would really help me diagnose the issue.

**Comment by sorentwo** [comment]
@take-five I've investigated the issue more and I have identified the problem, but I don't have a fix for it yet.

#### Confirmation

First, I created a simple test worker and lightweight setup that allowed me to run a similar job and the related queries locally. The code works within the oban repo itself, which allowed me to poke at it from iex:

```elixir
defmodule TestWorker do
  @moduledoc false

  use Oban.Worker, queue: :default

  @oban_uniqueness_config [
    period: 60 * 60 * 24,
    fields: [:worker, :queue],
    states: [:scheduled]
  ]

  def perform(args, _job) do
    Process.sleep(500)

    args
    |> __MODULE__.new(schedule_in: 1, unique: @oban_uniqueness_config)
    |> Oban.insert!()
  end
end

Logger.configure(level: :debug)

Oban.Test.Repo.start_link()

{:ok, _} = Oban.start_link(repo: Oban.Test.Repo, queues: [default: 10], verbose: :debug)
```

With a constant stream of jobs running I began inserting arbitrary jobs. After a batch of jobs was inserted I would measure the query time:

| jobs    | time   |
| ------- | ------ |
| 1,700   | 1.7ms  |
| 6,756   | 4.8ms  |
| 11,774  | 7.5ms  |
| 21,797  | 13.2ms |
| 31,818  | 17.8ms |
| 81,856  | 41.6ms |
| 131,964 | 62.4ms |

There was a clear upward trend based on the number of jobs in the database. As mentioned in the original issue, the query is plenty fast when called directly from psql.

#### Diagnosis

The fact that there is a difference between Ecto and psql led me to believe that prepared statements are to blame. To confirm I modified the repo's test config:

```elixir
config :oban, Oban.Test.Repo,
  priv: "test/support/",
  url: System.get_env("DATABASE_URL") || "postgres://localhost:5432/oban_test",
  pool_size: 1,
  prepare: :unnamed
```

Sure enough, when `prepare: :unnamed` is set the **query time doesn't increase**. The issue is definitely with the prepared statement. We can confirm that there is an issue with the prepared statement in psql and also in the console directly.

After the worker has been going a while in the console I checked postgres for details on all of the prepared statements:

```elixir
Oban.Test.Repo.query("SELECT * FROM pg_prepared_statements")
```

That query yielded all of the prepared statements along with their names. The query I was looking for was listed as `ecto_2306` (note, this is a slightly modified version of the query):

```elixir
     [
       "ecto_2306",
       "SELECT o0.\"id\", o0.\"state\", o0.\"queue\", o0.\"worker\", o0.\"args\", o0.\"errors\", o0.\"attempt\", o0.\"attempted_by\", o0.\"max_attempts\", o0.\"attempted_at\", o0.\"completed_at\", o0.\"inserted_at\", o0.\"scheduled_at\" FROM \"public\".\"oban_jobs\" AS o0 WHERE (o0.\"state\" = ANY($1)) AND (o0.\"inserted_at\" > now() at time zone 'utc' - interval '1 second' * $2) AND ((o0.\"worker\" = $3) AND (o0.\"queue\" = $4)) ORDER BY o0.\"id\" DESC LIMIT 1",
       ~U[2019-10-14 12:55:32.139567Z],
       [347211, 701, 25, 25],
       false
     ],
```

Using the statement's name I then examined the query plan:

```elixir
Oban.Test.Repo.query("EXPLAIN ANALYZE EXECUTE ecto_1028('{scheduled}', 86400, 'TestWorker', 'default')")
```

The explain output confirmed that this query was indeed slower, and it has a different plan than our regular non-prepared query:

```elixir
{:ok,
 %Postgrex.Result{
   columns: ["QUERY PLAN"],
   command: :explain,
   connection_id: 97277,
   messages: [],
   num_rows: 0,
   rows: [
     ["Limit  (cost=0.42..0.63 rows=1 width=150) (actual time=39.737..39.738 rows=0 loops=1)"],
     ["  ->  Index Scan Backward using oban_jobs_pkey on oban_jobs o0  (cost=0.42..10574.47 rows=50048 width=150) (actual time=39.734..39.734 rows=0 loops=1)"],
     ["        Filter: ((worker = $3) AND (queue = $4) AND (state = ANY ($1)) AND (inserted_at > (timezone('utc'::text, now()) - ('00:00:01'::interval * $2))))"],
     ["        Rows Removed by Filter: 150192"],
     ["Planning Time: 0.078 ms"],
     ["Execution Time: 39.870 ms"]
   ]
 }}
```

For reference, here is the explain output for the non-prepared query:

```
                                                                               QUERY PLAN
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
 Limit  (cost=15.58..15.59 rows=1 width=150) (actual time=0.079..0.079 rows=0 loops=1)
   ->  Sort  (cost=15.58..15.59 rows=1 width=150) (actual time=0.078..0.078 rows=0 loops=1)
         Sort Key: id DESC
         Sort Method: quicksort  Memory: 25kB
         ->  Index Scan using oban_jobs_queue_state_scheduled_at_id_index on oban_jobs o0  (cost=0.42..15.57 rows=1 width=150) (actual time=0.041..0.041 rows=0 loops=1)
               Index Cond: ((queue = 'default'::text) AND (state = ANY ('{scheduled}'::oban_job_state[])))
               Filter: ((worker = 'TestWorker'::text) AND (inserted_at > (now() + '24:00:00'::interval)))
 Planning Time: 0.166 ms
 Execution Time: 0.123 ms
(9 rows)
```

As an additional note, the first 5 times the planned query is called it is extremely fast. Is only on the sixth call that it gets slower. We can see in the [PostgreSQL documentation](https://www.postgresql.org/docs/current/sql-prepare.html) that this is because it switches execution from a _custom plan_ to a _generic plan_:

> By default (that is, when plan_cache_mode is set to auto), the server will automatically choose whether to use a generic or custom plan for a prepared statement that has parameters. The current rule for this is that the first five executions are done with custom plans and the average estimated cost of those plans is calculated. Then a generic plan is created and its estimated cost is compared to the average custom-plan cost. Subsequent executions use the generic plan if its cost is not so much higher than the average custom-plan cost as to make repeated replanning seem preferable.

#### Fixing

I am working on a way to modify the query so the planner makes a better decision. In the meantime the only fix I know of is to disable prepared statements through the `:unnamed` setting.

**Comment by take-five** [comment]
@sorentwo Thank you for the detailed analysis! To alleviate the issue we changed the pruning strategy to keep only last 1000 completed/discarded jobs in the table, but a proper fix would be nice to have.

Thanks for your help!

**Comment by nickjj** [comment]
> In the meantime the only fix I know of is to disable prepared statements through the :unnamed setting.

Sorry if this isn't the right spot for this question but what are the implications of making this change? Will it cause race conditions, other performance issues, etc.? If this is the proposed fix for now, why wouldn't this be the default if it's not affected by this issue?

**Comment by sorentwo** [comment]
> Sorry if this isn't the right spot for this question but what are the implications of making this change?

This is absolutely the right spot to ask. Honestly, in my experience there is virtually no impact from making this change. I've found that the application memory bloat that is caused by prepared statements far outweighs the minor performance improvements.

> Will it cause race conditions, other performance issues, etc.?

No, it doesn't cause any race conditions. Disabling prepared statements is standard practice if you're using connection pooling (i.e. pg_bouncer).

> If this is the proposed fix for now, why wouldn't this be the default if it's not affected by this issue?

The `:unnamed` setting is passed to your Ecto pool when you start it. There isn't anything Oban can do to prevent prepared statements after you've started it.

As to why this isn't the default, I'm not sure. Prepared statements are usually faster, even if just by a little bit. This issue is quite rare (at least it's the first time I've seen such a drastic difference).

What I'd like to see (and will investigate) is the ability to prevent prepared statements at the transaction level. That probably involves changes to db_connection, postgrex and ecto though, so I'm not holding by breath.

**Comment by sorentwo** [comment]
@take-five It has been a while, but a workaround finally occurred to me. Hopefully I can find something more straightforward in the future!

**Comment by nickjj** [comment]
For clarity the manual workaround of setting `prepare: :unnamed` is no longer needed?

**Comment by sorentwo** [comment]
@nickjj Correct, it isn't required anymore. Depending on your workload and how you configured the `unique` opts it may not have been necessary before either. For instance, if you included `args` in the unique fields it would use a custom plan regardless.

**Comment by take-five** [comment]
Thank you @sorentwo, I've updated Oban in production and now monitoring the performance. I'll let you know how the things are going.

**Comment by take-five** [comment]
Hi @sorentwo !
I've let the new version run in production for a day and removed the limit on the job history size and here's how the graph looks like:
![image](https://user-images.githubusercontent.com/1209413/68949769-77507480-07c3-11ea-95bc-e9c705de5711.png)

I'm afraid the problem is still there ?

**Comment by sorentwo** [comment]
@take-five Hmm. The purple doesn't look like it is increasing nearly as quickly as before. A few questions:

1. How many jobs are in the table now?
2. If you look at the unique query time immediately after a restart are the queries really fast for 5 calls and then immediately slow?

**Comment by take-five** [comment]
1. There are 28k jobs in the table at the moment
2. I don't think so, no. At least it's not visible on the graph:
![image](https://user-images.githubusercontent.com/1209413/68951373-91d81d00-07c6-11ea-9b66-6514a98e5a8c.png)

Sorry for stupid question, but is this change included into the latest release?
I can't see it the commits history for 0.11.1: https://github.com/sorentwo/oban/commits/v0.11.1

**Comment by sorentwo** [comment]
> Sorry for stupid question, but is this change included into the latest release?

Not a stupid question at all. This change is only in master, it is not included in `v0.11.1`. I was hoping you would verify the change (on master) before I released a fix.

**Comment by take-five** [comment]
Oh, sorry, I acted on the assumption that it's already released. I'll give it a try on Monday and get back to you after that. Sorry for the misunderstanding.

**Comment by sorentwo** [comment]
Whew! You had me worried there. 😅

No rush, thanks for all the help.

**Comment by take-five** [comment]
I've deployed the fix and I can see it definitely helped:
![image](https://user-images.githubusercontent.com/1209413/69046144-f8487f80-0a00-11ea-94eb-bfa5494c1d70.png)

Thanks for fixing it, @sorentwo !

P.S. One interesting moment about this problem. I was trying to replicate it in `psql`, I prepared a query and then I was trying to `explain analyze execute q1 (...)`, but it never fell back to a generic plan. I wonder if it's Ecto-specific or not.

**Comment by sorentwo** [comment]
Awesome! Worked as planned.

> P.S. One interesting moment about this problem. I was trying to replicate it in `psql`, I prepared a query and then I was trying to `explain analyze execute q1 (...)`, but it never fell back to a generic plan. I wonder if it's Ecto-specific or not.

It shouldn't be Ecto specific. I could definitely recreate this before with the commands I posted above.
