### ISSUE TITLE
Postgres notifier exceeds pg_notify character limit

### ISSUE THREAD

**Issue by halfdan** [sorentwo/oban#791]
We are seeing a lot of errors originating from [this](https://github.com/sorentwo/oban/blob/main/lib/oban/notifiers/postgres.ex#L101) query. It seems that oban somehow manages to exceed the 8000 character limit of pg_notify. 

### Environment

- Oban Version: 2.13.3
- PostgreSQL Version: 13.5
- Elixir & Erlang/OTP Versions (`elixir --version`): 
    Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
    Elixir 1.13.4 (compiled with Erlang/OTP 23)

### Current Behavior

Include code samples, errors and stacktraces if appropriate.

![image](https://user-images.githubusercontent.com/176576/196400052-36d54148-b977-4648-b1fd-81329f066efa.png)

### Expected Behavior

Unclear.

**Comment by sorentwo** [comment]
@halfdan I did a little experimentation to see if the payload size was per `pg_notify` call or cumulative for the channel or transaction. It's per `pg_notify` call, which means a single gossip message is over the 8kb limit. I think this is probably from a large meta map with partition information.

There isn't any way to bypass the notification size limit, so I'll investigate pruning or truncating the gossip messages. In the meantime, if possible, I suggest using the `PG` notifier because it doesn't have any size restrictions.
