### ISSUE TITLE
Shitty support

### ISSUE THREAD

**Issue by ally9335** [sorentwo/oban#822]
Half of my initial answers were ansered by email, by some lady, but other half weren't.  Despite back and forth communication.

Your support is full of shit.

**Comment by sorentwo** [comment]
No idea who you are or what questions you asked. Sorry to hear you emailed for support and didn’t get the response you were looking for from _my wife and business partner_. Regardless, there is no excuse for you to open an issue on a public tracker to insult people.

If you’re a paying customer please email again and we’ll address your questions. Otherwise, we don’t owe you any support and you’ll have to ask elsewhere.
