### ISSUE TITLE
Register callback to execute at the end of jobs

### ISSUE THREAD

**Issue by ylasnier** [sorentwo/oban#835]
### Is your feature request related to a problem? Please describe.

I'd like to execute code at the end of all jobs (e.g. push custom metrics like memory usage to elasticsearch), without being forced to add it at the end of each `perform/1` implementation.

### Describe the Solution You'd Like

A way to register a callback to execute at the end of jobs.

### Describe Alternatives You've Considered

Add memory usage in telemetry events.

### Additional Context

In Plug, there is `Plug.Conn.register_before_send/2` : https://hexdocs.pm/plug/Plug.Conn.html#register_before_send/2

**Comment by sorentwo** [comment]
@ylasnier Thanks for the suggestion. This feature request has come up fairly often, and it's trickier than it sounds. That's why the `Oban.Pro.Worker` module, provided by Oban Pro, has global, local, and implicit [Worker Hooks](https://getoban.pro/docs/pro/0.13.0/Oban.Pro.Worker.html#module-worker-hooks) that offer the functionality you're looking for.
