### ISSUE TITLE
How to repeat a job?

### ISSUE THREAD

**Issue by satyavh** [sorentwo/oban#95]
What is the best way to repeat (as in, reschedule somewhere in the future) a running job? 
Can it update its own scheduled_at and set its status again to available? 
Or should it simply create a new job?

**Comment by sorentwo** [comment]
> Can it update its own scheduled_at and set its status again to available?

No, that won't work because regardless of what `state` you set it to while the job is executing, it job will be marked `completed` when it finishes.

> Or should it simply create a new job?

Most likely. However, if this is something you expect to do frequently, I suggest using an error tuple and a custom backoff strategy to fail the job and schedule it for retry later. There are more details about that approach in the [expected failures recipe](https://sorentwo.com/2019/10/17/oban-recipes-part-6-expected-failures.html).

**Comment by satyavh** [comment]
Thanks for your quick answer. Those blog posts are very helpful!

Ps, great package, should be listed here https://github.com/h4cc/awesome-elixir
