### ISSUE TITLE
Flooded with Oban errors in Sentry since upgrading (see description for versions)

### ISSUE THREAD

**Issue by coop** [sorentwo/oban#982]
### Environment

- Oban Version: 2.16.3
- Oban Pro Version: 1.1.5
- Oban Web Version: 2.10.0
- PostgreSQL Version: 15.3
- Elixir Version: 1.15.7
- Erlang Version: 26.1.2

### Current Behavior

Since upgrading to the above mentioned oban versions from oban 2.15.1, oban pro: 0.14.2 and oban web 2.9.7 I am seeing many many sentry errors due to gen_statem timeouts, unhandled pattern matching and (I think) intermittent DB connections:

<img width="1281" alt="Screenshot 2023-11-07 at 7 42 29 pm" src="https://github.com/sorentwo/oban/assets/64469/6027cc08-1c44-4837-ae53-9ef7836e1ac3">

I realise that this is just an overview, here are a few of the stacktraces:

<img width="945" alt="image" src="https://github.com/sorentwo/oban/assets/64469/c83a5965-574d-4257-9b0b-08f2cd173fa4">

<img width="935" alt="image" src="https://github.com/sorentwo/oban/assets/64469/bfee01b9-37dc-40b5-8cb0-e2d9db380d99">

<img width="948" alt="image" src="https://github.com/sorentwo/oban/assets/64469/e228363f-0b21-4008-8157-527c504a9b0e">

<img width="938" alt="image" src="https://github.com/sorentwo/oban/assets/64469/f5ec711f-1d2f-487a-836b-95d4af2c2bf7">

I used to get the odd message in Sentry that one of the Oban processes crashed for some reason or another but since upgrading almost every error in sentry is related to Oban code I can look at but can't contribute to.

### Oban Configuration

I run a fairly standard application on fly.io. There are 3 machines in the cluster, each machine runs oban. Here is the configuration passed to `Oban.start_link/1`:

```elixir
[
  name: Oban,
  repo: MyAoo.Repo,
  engine: Oban.Pro.Engines.Smart
  queues: [
    default: 10
  ],
  plugins: [
    Oban.Pro.Plugins.DynamicLifeline,
    Oban.Pro.Plugins.DynamicPruner,
    {Oban.Plugins.Cron,
     crontab: [
        # ... a couple of workres
     ]}
  ]
]
```

### Expected Behavior

Not to blow up sentry.

**Comment by sorentwo** [comment]
I'm sorry to hear your Sentry blew up.

> since upgrading almost every error in sentry is related to Oban code I can look at but can't contribute to

All of those errors are coming from `postgrex` notification timeouts. `Postgrex.SimpleConnection` uses `:gen_statem`, and Oban uses `SimpleConnection`  for PubSub notifications in many places, including plugins like `Stager`. For reference, the Postgres notifier is open source: https://github.com/sorentwo/oban/blob/main/lib/oban/notifiers/postgres.ex.

The issue here is with database timeouts and not with changes in Oban. Perhaps you have upgraded `postgrex` along with the other package upgrades, and the change to `:gen_statem` highlighted underlying timing issues?

Postgres is a decent default for PubSub, but it has drawbacks, including connectivity pressures, as you've discovered. Since you're on fly.io and likely distributed, I highly recommend switching to the [PG notifier](https://hexdocs.pm/oban/Oban.Notifiers.PG.html).

```elixir
notifier: Oban.Notifiers.PG,
```
